### ISSUE TITLE
what does the prefix "rps_" mean? 

### ISSUE THREAD

**Issue by bpwl0121** [togethercomputer/RedPajama-Data#114]
Hi,

thanks for the text toolkit !
but a question just regarding the prefix "rps_", it is RP signal? what is rp actually?

thanks.

**Comment by mauriceweber** [comment]
Hi @bpwl0121 , that's correct:) RP stands for RedPajama.

**Comment by bpwl0121** [comment]
> Hi @bpwl0121 , that's correct:) RP stands for RedPajama.

aha, I see. RP for RedPajama. ;)
