### ISSUE TITLE
Guide how to use

### ISSUE THREAD

**Issue by kamalkech** [togethercomputer/RedPajama-Data#13]
Can you share link of guide how to use this model ??

**Comment by ericborgos** [comment]
It is not a model, it is a bunch of Python files you can run to create a dataset in the format needed to train an LLM such as LLaMA. None of the code has to do with actually training a model, which you would do with something like GPT-NeoX-20B.

**Comment by mauriceweber** [comment]
Yes, this repo allows you to create the dataset used to train LLaMA like models.
