### ISSUE TITLE
Hashes to verify download integrity

### ISSUE THREAD

**Issue by carlini** [togethercomputer/RedPajama-Data#15]
I've downloaded the dataset with `wget -i https://data.together.xyz/redpajama-data-1T/v1.0.0/urls.txt`. I'd like to make sure that I got everything correctly. Any chance you could release some form of CRC/MD5/SHA hashes to make sure I didn't download any corrupted files? (I'm not worried about needing cryptographic hashes because of some adversary given that this data is all self hosted. I'm mainly worried I've had a file truncated or something.)

**Comment by mauriceweber** [comment]
We released SHA256 checksums for each slice, you can check out the discussion on HF: https://huggingface.co/datasets/togethercomputer/RedPajama-Data-1T/discussions/2

let me know if this works for you!:)

**Comment by carlini** [comment]
Thank you! I will verify my hashes from this.
