### ISSUE TITLE
will there be a trained model?

### ISSUE THREAD

**Issue by rozek** [togethercomputer/RedPajama-Data#19]
First of all: thank you very much for your contribution!

That said, I still have a question: in order to really "democratise" AI, a trained model will be needed that may be used for (fine-tuning and) inference - not too many people have the resources to train a new model from scratch.

Will such a model be made available? And, if yes, do you have any idea when?

Thanks in advance for your effort!

Andreas Rozek

**Comment by fnpanic** [comment]
As you stated correctly it requires massive amount of compute ressources to train a model with this dataset from scratch. According to the blogpost from together i would guess it is already in training:

*Having reproduced the pre-training data, the next step is to train a strong base model. As part of the [INCITE program](https://www.alcf.anl.gov/science/incite-allocation-program), with support from [Oak Ridge Leadership Computing Facility (OLCF)](https://www.olcf.ornl.gov/), we are training a full suite of models, with the first becoming available in the coming weeks.*

source: https://www.together.xyz/blog/redpajama
