### ISSUE TITLE
Please consider adding a source of natural dialogue data

### ISSUE THREAD

**Issue by wassname** [togethercomputer/RedPajama-Data#22]
Many of the open source datasets are missing natural dialogue data. As a result, the models seem less genuine, less interesting, and less able to chat.

Another way to say this: I just searched "baby cry after 6 week vaccines" and found a bunch of vague articles with generic advice, on the other hand "baby cry after 6 week vaccines reddit" lead my wife and I to some very helpful r/beyondthebump conversations. And that's because natural dialogue is a very high signal data source! 

I'd like AI's trained on this dataset to be able to be just as direct and helpful. So I propose including a few T tokens of reddit comments. Perhaps selected from the higher quality subreddits (writingprompts, science, changemymind, askscience, etc).

The largest dataset of dialogue data is reddit so I'd like to propose that you include reddit data
- 2TB of comments including everything up to now on academictorrents
- (just from high quality subreddits) https://huggingface.co/datasets/stanfordnlp/SHP
- up unto 2020 on [bigquery](https://old.reddit.com/r/bigquery/comments/3cej2b/17_billion_reddit_comments_loaded_on_bigquery/) and all on pushshift.io

There are also other dialogue datasets
- [hackernews](https://console.cloud.google.com/marketplace/product/y-combinator/hacker-news?project=scrape-reddit-comments)
- [prosocial dialogue](https://huggingface.co/datasets/allenai/prosocial-dialog)
- [oig-dataset](https://laion.ai/blog/oig-dataset/)
- [Quora Question Pairs Dataset](https://paperswithcode.com/dataset/quora-question-pairs)

Thoughts? Would you merge a PR on this?

**Comment by mauriceweber** [comment]
Hi @wassname and thanks for bringing this up.

We are working on instruction tuning so that the quality of the model will improve for chat-like tasks; this will be more on the finetuning side (i.e. to make the basic LLM more chat-like), rather than pretraining. We will release more details about this in the coming weeks!

**Comment by wassname** [comment]
Ah it sounds my suggestion was a bit late. Good luck with the training, with LLM's it's no easy feat. :four_leaf_clover:
