### ISSUE TITLE
where is the FastText ptrtrained model to  classify each CommonCrawl webpage

### ISSUE THREAD

**Issue by yuhai-china** [togethercomputer/RedPajama-Data#24]
First of all: thank you very much for your contribution!

Many thanks if you can share  the FastText ptrtrained model to  classify each CommonCrawl webpage whether it is low quality page

**Comment by xzyaoi** [comment]
You can download it here: https://fasttext.cc/docs/en/language-identification.html

**Comment by yuhai-china** [comment]
> You can download it here: https://fasttext.cc/docs/en/language-identification.html

thanks, I want to find the mode to classify the web page whether it is low quality  instead of language identification

**Comment by Ivan-Zhou** [comment]
Hi, @yuhai-china Here's the model file that we trained ([link](https://drive.google.com/file/d/1DnsfpWWE0jFPCoYe6clwqb3Ub5Ac92s1/view?usp=share_link)). You can use the script [here](https://github.com/togethercomputer/RedPajama-Data/blob/main/data_prep/cc/classifier/classify.py) to load the model and run inference. 

I will also add the link of the model weight to our README.

**Comment by yuhai-china** [comment]
> Hi, @yuhai-china Here's the model file that we trained ([link](https://drive.google.com/file/d/1DnsfpWWE0jFPCoYe6clwqb3Ub5Ac92s1/view?usp=share_link)). You can use the script [here](https://github.com/togethercomputer/RedPajama-Data/blob/main/data_prep/cc/classifier/classify.py) to load the model and run inference.
> 
> I will also add the link of the model weight to our README.

thank you very much. it works well
