### ISSUE TITLE
Add missing script or update README.md

### ISSUE THREAD

**Issue by geoffreydstewart** [togethercomputer/RedPajama-Data#27]
Thanks for your great work on this project! As mentioned in #25 The script `scripts/github-prepare-download.sh` which is referenced in [this README.md](https://github.com/togethercomputer/RedPajama-Data/blob/main/data_prep/github/README.md) is not present in the repository. Should the file be added, or is the README.md incorrect?
Thanks!

**Comment by mauriceweber** [comment]
Hi @geoffreydstewart, the script is here: https://github.com/togethercomputer/RedPajama-Data/blob/main/data_prep/github/scripts/github-prepare-download.sh

The script gets a list of the files in your gcp bucket and splits these into different chunks so that you can download the chunks in parallel.

**Comment by geoffreydstewart** [comment]
Yes, it most certainly is! I'm not sure why that wasn't showing up in my IDE, but it's there on my file system. Sorry for the noise.

**Comment by mauriceweber** [comment]
cool!:)
