### ISSUE TITLE
If the program exit with the outside cause

### ISSUE THREAD

**Issue by 1787648106** [togethercomputer/RedPajama-Data#30]
If the program terminates due to a power outage when I run the cc-net data prepare pipline, how can it continue execution at the breakpoint when restarted?

**Comment by mauriceweber** [comment]
The pipeline will skip the files it has already processed. Check out the `mine` function [here](https://github.com/togethercomputer/RedPajama-Data/blob/1ca78198e9177889e4651c9754c1556027f3be54/data_prep/cc/cc_net/cc_net/mine.py#L286).
