### ISSUE TITLE
No file named github-prepare-local-dedup.sh

### ISSUE THREAD

**Issue by feverdreamy** [togethercomputer/RedPajama-Data#53]
Hey, I've been trying to process and clean the dataset for awhile now and I keep getting this error and can't seem to find the file in the repo or anything. Any help would be greatly appreciated. Here is the error message - bash: scripts/github-prepare-local-dedup.sh: No such file or directory

**Comment by mauriceweber** [comment]
Hi @feverdreamy thanks for bringing this up! This is a typo in the readme and should be `bash scripts/github-prepare-clean.sh`. I just fixed it in d174968.
