### ISSUE TITLE
Memory requirement for book deduplication?

### ISSUE THREAD

**Issue by HYLcool** [togethercomputer/RedPajama-Data#55]
Hi, I tried the data preparation process of books using my server, which has over 100 cores and about 200GB memory.

When I run the [dedup.py](https://github.com/togethercomputer/RedPajama-Data/blob/main/data_prep/book/dedup.py) with the default parameters you provided (w=6, k=5, l=0, n=100), "Out of memory" problem occurs. And even I decreased the number of processes to 8. OOM still happens after processing several splits.

So could you please tell me that how much memory did you use when applying deduplication process on books? And how much time did it take to finish the whole process? Thanks!

**Comment by mauriceweber** [comment]
Hi @HYLcool , we used 112 cores with 448G memory. It took ~24 hours to run the deduplicatino

**Comment by HYLcool** [comment]
Got it. Thanks for your reply! @mauriceweber
