### ISSUE TITLE
What is the cutoff.csv file mentioned in data_prep/cc/cc_net/cc_net/mine.py?

### ISSUE THREAD

**Issue by julienliang2740** [togethercomputer/RedPajama-Data#57]
In mine.py on lines 32-34 it introduces this file called cutoff.csv:
<html>
<body>

# Constant
--
33 | FILE_DIR = Path(__file__).parent
34 | CUTOFF_CSV = FILE_DIR / "data" / "cutoff.csv"
35 |  
36 | DEFAULT_PIPELINE = [
37 | "dedup",
 
68 | cutoff: cutoff file to use for split in head/middle/tail
 
93 | cutoff: Path = CUTOFF_CSV
 
412 | steps["pp_bucket"] = perplexity.PerplexityBucket(CUTOFF_CSV)

</body>
</html>

It doesn't seem to come with the repository or be generated anywhere, it's also critical for classifying head, middle, tail, does anybody know what the file is like, so perhaps I can manually write out the file? Thanks!

**Comment by julienliang2740** [comment]
I see that somebody else had a similar issue, but is this a file that's just missing or something that should be generated?

**Comment by newbietuan** [comment]
> I see that somebody else had a similar issue, but is this a file that's just missing or something that should be generated?

it seems a file that contains different languages' ppl to split the result to head, middle and tail.
