### ISSUE TITLE
Fine tuning RedPajama Model

### ISSUE THREAD

**Issue by adjhawar** [togethercomputer/RedPajama-Data#61]
Hi,
How do I finetune the RedPajama on my dataset? Is there a training script that ai can reuse?

**Comment by mauriceweber** [comment]
You can use the finetuning scripts in https://github.com/togethercomputer/OpenChatKit. 

There is also a section in our blog post that explains how to use the scripts to finetune the  RP-INCITE chat models [here](https://www.together.xyz/blog/redpajama-3b-updates#:~:text=Fine%2Dtuning%20RedPajama%2DINCITE%2D3B%20models).
