### ISSUE TITLE
Train a new wikiref model

### ISSUE THREAD

**Issue by torshie** [togethercomputer/RedPajama-Data#91]
I want to apply this pipeline to a new language, but I cannot find a wikipedia reference classifier model for the language.

How is the English wikipedia reference model trained ? Any docs/links/suggestions ?

Thanks.

**Comment by mauriceweber** [comment]
Hi @torshie , we used the wikipedia reference classifier from RedPajama-v1. To train such a classifier, you can use the code in the rp_v1 branch [here](https://github.com/togethercomputer/RedPajama-Data/tree/rp_v1/data_prep/cc) -- in `data_prep/cc/classifier/` you will find code to train the wikipedia references classifier.
