### ISSUE TITLE
Impossible unpack tail data... took time to download, but impossible to unpack dataset without quality signals with broken link.

### ISSUE THREAD

**Issue by RuslanKovalyov** [togethercomputer/RedPajama-Data#94]
An error occurred while processing the 'common_crawl' configuration: Couldn't find file at https://data.together.xyz/redpajama-data-v2/v1.0.0/quality_signals/2023-14/0000/en_tail.signals.json.gz

_____

open link with browser:
Error 404
This object could not be viewed

**Comment by lipingtang17** [comment]
It seems that the authors did not generate quality signals for tail data.
![image](https://github.com/togethercomputer/RedPajama-Data/assets/45155098/f18b8236-1825-4bf7-8582-e86629079062)
