### ISSUE TITLE
Are shards randomly created?

### ISSUE THREAD

**Issue by virendrakabra14** [togethercomputer/RedPajama-Data#95]
The 2023-14 snapshot contains 5000 shards.

Are these shards random - or created on some quality signal?

**Comment by mauriceweber** [comment]
These shards are random and come from the CCNet pipeline -- ccnet essentially groups web documents into shards which are processed in parallel and within wich it deduplicates paragraphs of the documents. The quality signals are computed on the output of the ccnet pipeline.
