### ISSUE TITLE
Is there a specific meaning of the snapshot id?

### ISSUE THREAD

**Issue by zijwang** [togethercomputer/RedPajama-Data#98]
For example, what does 14 mean in the last snapshot `2023-14`?

**Comment by mauriceweber** [comment]
Hi @zijwang , yes the snapshot id is composed of the year (2023) and the calendar week in which the crawl was released by CommonCrawl (week 14 in 2023-14).

**Comment by zijwang** [comment]
Thanks @mauriceweber  That makes sense to me :)
